# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: ''
google_analytics: '' 
title: d0ktrd4n''s notes

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: dbyll

description: d0ktrd4n''s notes
author:
  name: d0ktrd4n  
  email: d0ktrd4n@pm.me
  github: d0ktrd4n
  twitter: 
  pinterest: 
  linkedin: 
  bio: Security Researcher, Pentester, Nerd
  email_md5: 7bc58fefdbafe5af8eea09bd499058ca

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
